# Assignment 1:
### - The automated_stat_analyzer Function
- Scenario: A retail company needs a utility to quickly summarize sales data. Students must create a function that identifies the 
"Central Tendency" and "Dispersion" of any numerical column.
- ### Requirements:

* Accept a Pandas DataFrame and a column name.

* Calculate the Mean, Median, and Standard Deviation .

* Identify if the data is "Skewed" by comparing the Mean and Median.


* Bonus: If the column is categorical, return the Mode instead.

### Your Data

In [21]:
import pandas as pd

def automated_stat_analyzer(df, column_name):
    """
    Company Task: Provide a summary report of a specific data variable.
    
    Instructions:
    1. Check if the column is numerical or categorical.
    2. For numerical: Calculate Mean, Median, and Standard Deviation.
    3. For categorical: Calculate the Mode.
    4. Return a dictionary with these statistical measures.
    """
    # TODO: Implement using df[column_name].mean(), .median(), .std(), or .mode()  you can used Sales_Amount for your test case
    
    def automated_stat_analyzer(df, column_name):
     """
    Company Task: Provide a summary report of a specific data variable.
    
    Instructions:
    1. Check if the column is numerical or categorical.
    2. For numerical: Calculate Mean, Median, and Standard Deviation.
    3. For categorical: Calculate the Mode.
    4. Return a dictionary with these statistical measures.
     """

    try:
        if column_name not in df.columns:
            raise ValueError("Column does not exist in DataFrame")

        column = df[column_name]

        result = {}

        if pd.api.types.is_numeric_dtype(column):

            mean_val = column.mean()
            median_val = column.median()
            std_val = column.std()

            if mean_val > median_val:
                skewness = "Right Skewed"
            elif mean_val < median_val:
                skewness = "Left Skewed"
            else:
                skewness = "Symmetric"

            result = {
                "Type": "Numerical",
                "Mean": mean_val,
                "Median": median_val,
                "Standard Deviation": std_val,
                "Skewness": skewness
            }

        else:

            mode_val = column.mode()

            result = {
                "Type": "Categorical",
                "Mode": mode_val.iloc[0] if not mode_val.empty else None
            }

        return result

    except Exception as e:
        raise ValueError(f"Company-grade Error: {e}")

In [22]:
df_test.head()

   Transaction_ID Product_Category  Sales_Amount  Customer_Age  Rating
0               1      Electronics           150          25.0       5
1               2             Home           200          34.0       4
2               3      Electronics           155           NaN       3
3               4           Sports           300          45.0       5
4               5             Home           210          23.0       2

In [23]:
import pandas as pd

def automated_stat_analyzer(df, column_name):
    """
    Company Task: Provide a summary report of a specific data variable.
    
    Instructions:
    1. Check if the column is numerical or categorical.
    2. For numerical: Calculate Mean, Median, and Standard Deviation.
    3. For categorical: Calculate the Mode.
    4. Return a dictionary with these statistical measures.
    """
   
    # TODO: Implement using df[column_name].mean(), .median(), .std(), or .mode()  you can used Sales_Amount for your test case
    
    def automated_stat_analyzer(df, column_name):
      """
    Company Task: Provide a summary report of a specific data variable.
    
    Instructions:
    1. Check if the column is numerical or categorical.
    2. For numerical: Calculate Mean, Median, and Standard Deviation.
    3. For categorical: Calculate the Mode.
    4. Return a dictionary with these statistical measures.
      """

    try:
        if column_name not in df.columns:
            raise ValueError("Column does not exist in DataFrame")

        column = df[column_name]

        result = {}

       
        if pd.api.types.is_numeric_dtype(column):

            mean_val = column.mean()
            median_val = column.median()
            std_val = column.std()

        
            if mean_val > median_val:
                skewness = "Right Skewed"
            elif mean_val < median_val:
                skewness = "Left Skewed"
            else:
                skewness = "Symmetric"

            result = {
                "Type": "Numerical",
                "Mean": mean_val,
                "Median": median_val,
                "Standard Deviation": std_val,
                "Skewness": skewness
            }

       
        else:

            mode_val = column.mode()

            result = {
                "Type": "Categorical",
                "Mode": mode_val.iloc[0] if not mode_val.empty else None
            }

        return result

    except Exception as e:
        raise ValueError(f"Company-grade Error: {e}")

In [24]:
automated_stat_analyzer(df_test, "Sales_Amount")

{'Type': 'Numerical',
 'Mean': np.float64(275.0),
 'Median': np.float64(195.0),
 'Standard Deviation': np.float64(258.30645021412494),
 'Skewness': 'Right Skewed'}

In [25]:
automated_stat_analyzer(df_test, "Product_Category")

{'Type': 'Categorical', 'Mode': 'Electronics'}

## Assignment 2: 
  ### The null_handling_strategy Function

#### Scenario: Incoming user data often has missing values.Students must implement a flexible strategy to handle these "Null Values" to prepare data for Machine Learning.
### Requirements:

* Check for null values in the DataFrame.

* Apply a strategy based on parameters: "drop_rows", "fill_mean", or "fill_median" .

* Ensure the function only fills numerical columns when using mean or median.

In [26]:
def null_handling_strategy(df, strategy="fill_mean"):
    """
    Company Task: Clean a dataset by resolving missing (NaN) values.
    """
    # TODO: Implement using .isnull(), .dropna(), or .fillna() you can used Customer_Age for your test case
    
    
    def null_handling_strategy(df, strategy="fill_mean"):
     """
    Company Task: Clean a dataset by resolving missing (NaN) values.
     """
    try:
       
        cleaned_df = df.copy()
        if not cleaned_df.isnull().values.any():
            return cleaned_df

        if strategy == "drop_rows":

            cleaned_df = cleaned_df.dropna()
        elif strategy == "fill_mean":

            numeric_cols = cleaned_df.select_dtypes(include=np.number)

            for col in numeric_cols.columns:
                mean_val = cleaned_df[col].mean()
                cleaned_df[col] = cleaned_df[col].fillna(mean_val)

        elif strategy == "fill_median":

            numeric_cols = cleaned_df.select_dtypes(include=np.number)

            for col in numeric_cols.columns:
                median_val = cleaned_df[col].median()
                cleaned_df[col] = cleaned_df[col].fillna(median_val)

        else:
            raise ValueError("Invalid strategy. Use: drop_rows, fill_mean, fill_median")

        return cleaned_df

    except Exception as e:
        raise ValueError(f"Company-grade Error: {e}")

In [27]:
null_handling_strategy(df_test, "drop_rows")

   Transaction_ID Product_Category  Sales_Amount  Customer_Age  Rating
0               1      Electronics           150          25.0       5
1               2             Home           200          34.0       4
3               4           Sports           300          45.0       5
4               5             Home           210          23.0       2
5               6      Electronics           180          31.0       4
6               7             Home           205          29.0       5
8               9      Electronics           190          38.0       4
9              10      Electronics           160          40.0       3

In [28]:
null_handling_strategy(df_test, "fill_mean")

   Transaction_ID Product_Category  Sales_Amount  Customer_Age  Rating
0               1      Electronics           150        25.000       5
1               2             Home           200        34.000       4
2               3      Electronics           155        33.125       3
3               4           Sports           300        45.000       5
4               5             Home           210        23.000       2
5               6      Electronics           180        31.000       4
6               7             Home           205        29.000       5
7               8           Sports          1000        33.125       2
8               9      Electronics           190        38.000       4
9              10      Electronics           160        40.000       3

In [29]:
null_handling_strategy(df_test, "fill_median")

   Transaction_ID Product_Category  Sales_Amount  Customer_Age  Rating
0               1      Electronics           150          25.0       5
1               2             Home           200          34.0       4
2               3      Electronics           155          32.5       3
3               4           Sports           300          45.0       5
4               5             Home           210          23.0       2
5               6      Electronics           180          31.0       4
6               7             Home           205          29.0       5
7               8           Sports          1000          32.5       2
8               9      Electronics           190          38.0       4
9              10      Electronics           160          40.0       3