In [2]:
import pandas as pd

In [3]:
s = pd.Series([1,2,3,4])
type(s)
s1= pd.Series([1,2,3,4], index =['A','B','C','D'])

In [4]:
s1

A    1
B    2
C    3
D    4
dtype: int64

In [5]:
data =[[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']
        ]
df = pd.DataFrame(data, columns=['ID','std_id','Dept'])
df

   ID  std_id Dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     444  xyz

In [21]:
df.columns

Index(['ID', 'std_id', 'Dept'], dtype='str')

In [37]:
index=['row1','row2','row3','row4']
df.index = index
display(df)

      ID  std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     444  xyz

In [53]:
class person:
    def __init__(self,name):
        self.name=name
    @property
    def getInfo(self):
        return f"my name is {self.name}"

In [69]:
p1 = person("sara")
p1.getInfo

'my name is sara'

In [85]:
df.dtypes

ID        int64
std_id    int64
Dept        str
dtype: object

In [101]:
df['Dept'].dtype

In [117]:
df['Dept'] = df['Dept'].astype('category')

In [133]:
df.dtypes

ID           int64
std_id       int64
Dept      category
dtype: object

In [149]:
df.head(2)

      ID  std_id Dept
row1   1     444  abc
row2   2     555  def

In [165]:
df.tail(2)

      ID  std_id Dept
row3   3     666  ghi
row4   4     444  xyz

In [181]:
df.describe()

             ID      std_id
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [197]:
df.describe(include='category')

       Dept
count     4
unique    4
top     abc
freq      1

In [213]:
df.columns

Index(['ID', 'std_id', 'Dept'], dtype='str')

In [214]:
x = df['std_id'].unique().sum()
x

np.int64(1665)

In [215]:
df['std_id'].min()

np.int64(444)

In [216]:
df.Dept.idxmin()

'row1'

In [217]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   std_id  4 non-null      int64
 2   Dept    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 476.0+ bytes

In [218]:
df['Dept'].value_counts()

Dept
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [219]:
df['ID'].sum()

np.int64(10)

In [220]:
def duplicate(x):
    return x *2

df['std_id'].apply(lambda x : x*2)

row1     888
row2    1110
row3    1332
row4     888
Name: std_id, dtype: int64

In [221]:
df['ID'].iloc[2]

np.int64(3)

In [222]:
df.iloc[2,1]

np.int64(666)

In [223]:
df.Dept.iloc[0:2]

row1    abc
row2    def
Name: Dept, dtype: category
Categories (4, str): ['abc', 'def', 'ghi', 'xyz']

In [224]:
df.iloc[:]

      ID  std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     444  xyz

In [225]:
df.iloc[: 0:2]

Empty DataFrame
Columns: [ID, std_id, Dept]
Index: []

In [226]:
num_col = df.iloc[: , 0:2]
cat_col =df.iloc[: , 2:3]

In [227]:
num_col = df.iloc[: , 0:-1]
target_y = df.iloc[: ,-1:]
num_col

      ID  std_id
row1   1     444
row2   2     555
row3   3     666
row4   4     444

In [229]:
df['new_col'] = df.std_id + df.ID
df

      ID  std_id Dept  new_col
row1   1     444  abc      445
row2   2     555  def      557
row3   3     666  ghi      669
row4   4     444  xyz      448

In [230]:
df.drop('new_col',axis=1)

      ID  std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     444  xyz

In [231]:
df.drop('row2',axis=0)

      ID  std_id Dept  new_col
row1   1     444  abc      445
row3   3     666  ghi      669
row4   4     444  xyz      448

In [232]:
df.isnull().sum()

ID         0
std_id     0
Dept       0
new_col    0
dtype: int64

In [233]:
import numpy as np

In [234]:
data=[[1,444,'abc'],[2,555,'def'],[3,666,'ghi'],[4,np.nan,'xyz']]
"""data_2={
    'ID':[1,2,3,4],
    'std_id_dict':[444,555,666,444],
    'Dept':['abc','def','ghi','xyz']}"""
df = pd.DataFrame(data,columns=['ID','std_id','Dept'])
display(df)

   ID  std_id Dept
0   1   444.0  abc
1   2   555.0  def
2   3   666.0  ghi
3   4     NaN  xyz

In [235]:
df.isnull().sum()

ID        0
std_id    1
Dept      0
dtype: int64

In [236]:
def isNull(df):
   null=df.isnull().sum()
   return pd.DataFrame(null).T

In [237]:
null=df.isnull().sum()
pd.DataFrame(null).T

   ID  std_id  Dept
0   0       1     0

In [239]:
from isNullval import is_Null
is_Null(df)

   ID  std_id  Dept
0   0       1     0