In [5]:
pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/64/2d/4f8a2f192ed12c90a0aab47f5557ece0e56b0370c49de9454a09de7381b2/pandas-3.0.0-cp312-cp312-win_amd64.whl.metadata
  Using cached pandas-3.0.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\modern\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\modern\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\modern\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\modern\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.0-cp312-cp312-win_amd64.whl (9.7 MB)
Installing collected packages: pandas
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\modern\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\common.py'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd

In [14]:
s = pd.Series([1,2,3,4])
type(s)
s1= pd.Series([1,2,3,4], index =['A','B','C','D'])

In [15]:
s1

A    1
B    2
C    3
D    4
dtype: int64

In [17]:
data =[[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']
        ]
df = pd.DataFrame(data, columns=['ID','std_id','Dept'])
df

   ID  std_id Dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     444  xyz

In [20]:
x = df['std_id'].unique().sum()
x

np.int64(1665)

In [21]:
df['std_id'].min()

np.int64(444)

In [23]:
df.Dept.idxmin()

0

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   std_id  4 non-null      int64
 2   Dept    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [25]:
df['Dept'].value_counts()

Dept
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [26]:
df['ID'].sum()

np.int64(10)

In [27]:
def duplicate(x):
    return x *2

df['std_id'].apply(lambda x : x*2)

0     888
1    1110
2    1332
3     888
Name: std_id, dtype: int64

In [28]:
df['ID'].iloc[2]

np.int64(3)

In [29]:
df.iloc[2,1]

np.int64(666)

In [30]:
df.Dept.iloc[0:2]

0    abc
1    def
Name: Dept, dtype: str

In [ ]:
df.iloc[:]

   ID  std_id Dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     444  xyz

In [32]:
df.iloc[: 0:2]

Empty DataFrame
Columns: [ID, std_id, Dept]
Index: []

In [36]:
num_col = df.iloc[: , 0:2]
cat_col =df.iloc[: , 2:3]

In [37]:
num_col = df.iloc[: , 0:-1]
target_y = df.iloc[: ,-1:]
num_col

   ID  std_id
0   1     444
1   2     555
2   3     666
3   4     444

In [39]:
df.drop(2, axis=0)

   ID  std_id Dept
0   1     444  abc
1   2     555  def
3   4     444  xyz